// Карта koff.ro категория -> слъг в case-king.bg (автоматично генерирана)
export const CATEGORY_MAP = {
  "CamShield Series": "keysove-i-kalufi",
  "SoftFlex": "keysove-i-kalufi",
  "Techsuit": "keysove-i-kalufi",
  "CamGuard Pro": "keysove-i-kalufi",
  "Carbon Silicone": "keysove-i-kalufi",
  "Shockproof Clear Silicone": "keysove-i-kalufi",
  "HaloFrost II MagSafe": "keysove-i-kalufi",
  "eFold Series": "keysove-i-kalufi",
  "CandyCase MagSafe": "keysove-i-kalufi",
  "Magic Shield": "keysove-i-kalufi",
  "ColorVerse 360 Series": "keysove-i-kalufi",
  "Luxury Crystal MagSafe": "keysove-i-kalufi",
  "SmartMag Book Case": "keysove-i-kalufi",
  "Luxury Glitter MagSafe": "keysove-i-kalufi",
  "Leather Folio": "keysove-i-kalufi",
  "Hardcase Series": "keysove-i-kalufi",
  "Ultra Hybrid": "keysove-i-kalufi",
  "FlipCraft": "keysove-i-kalufi",
  "Carbonite FiberShell": "keysove-i-kalufi",
  "Carbon Shield PRO": "keysove-i-kalufi",
  "SmartWatch Cases": "keysove-i-kalufi",
  "Clear Silicone": "keysove-i-kalufi",
  "IML Series": "keysove-i-kalufi",
  "Classic Series": "keysove-i-kalufi",
  "Magskin Book": "keysove-i-kalufi",
  "SmartView Series": "keysove-i-kalufi",
  "Glinth": "keysove-i-kalufi",
  "MagSafe Pro": "keysove-i-kalufi",
  "RuggedCam": "keysove-i-kalufi",
  "Diary Book": "keysove-i-kalufi",
  "Smart Protection": "keysove-i-kalufi",
  "Stand Series": "keysove-i-kalufi",
  "Confy Cover": "keysove-i-kalufi",
  "ArmorMag Case": "keysove-i-kalufi",
  "PureFrost MagSafe": "keysove-i-kalufi",
  "Wave Shield": "keysove-i-kalufi",
  "Safe Wallet Plus": "keysove-i-kalufi",
  "Spigen": "keysove-i-kalufi",
  "Leather Series": "keysove-i-kalufi",
  "Fusion": "keysove-i-kalufi",
  "Ringke": "keysove-i-kalufi",
  "Silicone Series": "keysove-i-kalufi",
  "Glitter Series": "keysove-i-kalufi",
  "Onyx": "keysove-i-kalufi",
  "Liquid Air": "keysove-i-kalufi",
  "Guess Mix": "keysove-i-kalufi",
  "Shockproof Clear Silicone MagSafe": "keysove-i-kalufi",
  "SoftFlex MagSafe": "keysove-i-kalufi",
  "Clear Case Series": "keysove-i-kalufi",
  "HoneyComb Shield MagSafe": "keysove-i-kalufi",
  "Tough Armor": "keysove-i-kalufi",
  "Saffiano Series": "keysove-i-kalufi",
  "SparkleSkin Series": "keysove-i-kalufi",
  "ColorVerse 360 MagSafe Series": "keysove-i-kalufi",
  "CarbonFiber": "keysove-i-kalufi",
  "Matt Case Series": "keysove-i-kalufi",
  "Armor Series": "keysove-i-kalufi",
  "Spigen Mix": "keysove-i-kalufi",
  "Flagship Series": "keysove-i-kalufi",
  "Cyber Armor": "keysove-i-kalufi",
  "Liquid Crystal": "keysove-i-kalufi",
  "Caseology Parallax": "keysove-i-kalufi",
  "Dux Ducis": "keysove-i-kalufi",
  "Hybrid Armor": "keysove-i-kalufi",
  "Karl Lagerfeld Mix": "keysove-i-kalufi",
  "Guardian Series": "keysove-i-kalufi",
  "ShellBox": "keysove-i-kalufi",
  "Silicone Magnetic MagSafe": "keysove-i-kalufi",
  "Rugged Armor": "keysove-i-kalufi",
  "Torras": "keysove-i-kalufi",
  "Monarch": "keysove-i-kalufi",
  "Marble Series": "keysove-i-kalufi",
  "Wallet Series": "keysove-i-kalufi",
  "Pathfinder": "keysove-i-kalufi",
  "Plyo": "keysove-i-kalufi",
  "Thin Fit": "keysove-i-kalufi",
  "HaloFrost Series": "keysove-i-kalufi",
  "Torras Mix": "keysove-i-kalufi",
  "Aramid Fiber MagSafe": "keysove-i-kalufi",
  "Waterproof Cases": "keysove-i-kalufi",
  "ESR Mix": "keysove-i-kalufi",
  "Fashionable Series": "keysove-i-kalufi",
  "Sparkly Glitter": "keysove-i-kalufi",
  "Fusion X": "keysove-i-kalufi",
  "Blueo": "keysove-i-kalufi",
  "Disco Series": "keysove-i-kalufi",
  "HaloFrost MagSafe Series": "keysove-i-kalufi",
  "UNIQ": "keysove-i-kalufi",
  "CamVault MagSafe": "keysove-i-kalufi",
  "Nillkin": "keysove-i-kalufi",
  "Civilian": "keysove-i-kalufi",
  "Frosty Series": "keysove-i-kalufi",
  "Sparkly Glitter MagSafe": "keysove-i-kalufi",
  "Slim Armor": "keysove-i-kalufi",
  "Zero HaloLock": "keysove-i-kalufi",
  "Silicone Shield": "keysove-i-kalufi",
  "Plasma": "keysove-i-kalufi",
  "Universal cases": "keysove-i-kalufi",
  "SparkleSkin MagSafe Series": "keysove-i-kalufi",
  "UAG": "keysove-i-kalufi",
  "Guess": "keysove-i-kalufi",
  "BMW": "keysove-i-kalufi",
  "Defense360 Pro": "keysove-i-kalufi",
  "SmartScreen NFC": "keysove-i-kalufi",
  "Glaze Series": "keysove-i-kalufi",
  "Power Pro Battery Case": "keysove-i-kalufi",
  "Essential Armor": "keysove-i-kalufi",
  "Mix Ringke": "keysove-i-kalufi",
  "UAG Mix": "keysove-i-kalufi",
  "3D Design": "keysove-i-kalufi",
  "Airpods/Galaxy Buds Cases": "keysove-i-kalufi",
  "Hello Kitty": "keysove-i-kalufi",
  "111D - Full Glue Glass": "protektori-za-ekran",
  "SmartWatch Screen Protectors": "protektori-za-ekran",
  "111D Privacy Full Glue": "protektori-za-ekran",
  "Full Camera Glass": "protektori-za-ekran",
  "Lens Protection": "protektori-za-ekran",
  "ESD Glass": "protektori-za-ekran",
  "Glas.tR EZ-FIT": "protektori-za-ekran",
  "FlexibleGlass": "protektori-za-ekran",
  "2.5D Screen Protector": "protektori-za-ekran",
  "Lens Protector": "protektori-za-ekran",
  "HD Glass": "protektori-za-ekran",
  "HardGlass": "protektori-za-ekran",
  "TitanGlass FullCover Privacy": "protektori-za-ekran",
  "ARC+ Series": "protektori-za-ekran",
  "Camera Glass": "protektori-za-ekran",
  "Optik.tR Camera Glass": "protektori-za-ekran",
  "Tempered Glass": "protektori-za-ekran",
  "Ultra-Wide": "protektori-za-ekran",
  "2.5D Classic Glass 9H - Clear": "protektori-za-ekran",
  "TitanGlass FullCover": "protektori-za-ekran",
  "D+ Max": "protektori-za-ekran",
  "3mk Mix": "protektori-za-ekran",
  "Armorite Screen Protector": "protektori-za-ekran",
  "Privacy Screen Protector": "protektori-za-ekran",
  "Anti-Peep Privacy Glass": "protektori-za-ekran",
  "Armorite Camera Lens Protectors": "protektori-za-ekran",
  "HD Pro Clear": "protektori-za-ekran",
  "TitanGlass CrystalHD": "protektori-za-ekran",
  "Camera Lens Protector": "protektori-za-ekran",
  "TitanGlass CrystalHD Privacy": "protektori-za-ekran",
  "Magic Glass Box D+ Tools - Clear": "protektori-za-ekran",
  "Anti-Reflective": "protektori-za-ekran",
  "Magic Glass Box D+ Tools - Privacy": "protektori-za-ekran",
  "Anti-Glare Glass": "protektori-za-ekran",
  "3D Screen Protector": "protektori-za-ekran",
  "3D Full Cover": "protektori-za-ekran",
  "Crystal Anti-Scratch Glass": "protektori-za-ekran",
  "3D Series": "protektori-za-ekran",
  "HD Pro Privacy": "protektori-za-ekran",
  "Clear Vision Glass": "protektori-za-ekran",
  "Glas.tR Align Master": "protektori-za-ekran",
  "ComfortDuo Glass + Case": "protektori-za-ekran",
  "3D UV Glass - Clear": "protektori-za-ekran",
  "Glass": "protektori-za-ekran",
  "2.5D FullGlue Glass": "protektori-za-ekran",
  "2.5D Classic Glass 9H - Privacy": "protektori-za-ekran",
  "Screen Protector Accessories": "protektori-za-ekran",
  "Glas.tR Slim": "protektori-za-ekran",
  "Sapphire Screen Protector": "protektori-za-ekran",
  "Corning UltraFit": "protektori-za-ekran",
  "D+ Pro Dustproof": "protektori-za-ekran",
  "D+ Pro Clear": "protektori-za-ekran",
  "D+ Pro Privacy": "protektori-za-ekran",
  "Neo Flex": "protektori-za-ekran",
  "NB Screen Protector": "protektori-za-ekran",
  "Lens Protector Tempered Glass": "protektori-za-ekran",
  "3D UV Glass - Privacy": "protektori-za-ekran",
  "Camera Protector": "protektori-za-ekran",
  "Car Holders": "aksesoari-za-avtomobili",
  "Car Chargers": "aksesoari-za-avtomobili",
  "Car Holders with Wireless Charging": "aksesoari-za-avtomobili",
  "Car Gadgets": "aksesoari-za-avtomobili",
  "Window Scappers": "aksesoari-za-avtomobili",
  "Wireless Desk Chargers": "bezzhichni-zaryadni",
  "Wall Chargers": "zaryadni-ustroystva",
  "SmartWatch Chargers": "zaryadni-ustroystva",
  "Travel Adapter": "zaryadni-ustroystva",
  "Type-C": "kabeli-za-zaryadane",
  "Lightning": "kabeli-za-zaryadane",
  "Mix 3in1": "kabeli-za-zaryadane",
  "Micro USB": "kabeli-za-zaryadane",
  "Desk Holders": "postavki-za-byuro",
  "Laptop Stands & Coolers": "postavki-za-byuro",
  "Selfie / Vlogging": "selfi-stikove",
  "Link Straps": "popsoket-i-vrazki",
  "Lanyard Strap": "popsoket-i-vrazki",
  "Lanyard Crossbody": "popsoket-i-vrazki",
  "Powerbanks": "vanshni-baterii"
};
